on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine
    - name: Build manylinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.5.0-manylinux2014_x86_64
      with:
        python-versions: 'cp39-cp39 cp310-cp310 cp311-cp311 cp312-cp312 cp313-cp313'
        system-packages: 'guile-devel zlib-devel gettext portaudio-devel portmidi-devel libsndfile-devel autogen libdb-devel wget'
        pre-build-command: 'sh manylinux-pre-build-script.sh'
        pip-wheel-args: '-w ./dist -config-setting="--build-option=--use-double" -config-setting="--build-option=--use-jack"'
    - name: Publish wheels to test PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: pypi-AgENdGVzdC5weXBpLm9yZwIkY2FkY2Y2MzktODE1NC00MDY1LTg5ZDctMzY0ODE1NGExYjgwAAILWzEsWyJweW8iXV0AAixbMixbIjJmMTZmZWQ3LTQ0ZmEtNGRmMC1hY2I0LTQ0M2ZmNDFkNzE5YiJdXQAABiD0UYJSUVETU3c-I0RJ8-E5Yi7dmtrH7fuMjngDX67khA
      run: |
        twine upload --verbose --repository testpypi dist/*-manylinux*.whl
